# name: Deploy Hourairos to ECS

# on:
#   push:
#     branches:
#       - main

# permissions:
#   id-token: write
#   contents: read

# env:
#   AWS_REGION: ap-south-1
#   ECR_REPOSITORY: hourairos/main-app
#   ECS_CLUSTER: hourairos-cluster
#   ECS_SERVICE: hourairous-app-fargate-service-z4p2puiy

# jobs:
#   deploy:
#     name: Build and Deploy
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout source code
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       # Step 2: Configure AWS credentials using OIDC
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: arn:aws:iam::851725373663:role/Github-OIDC-Access-role-ecs-ecr
#           aws-region: ${{ env.AWS_REGION }}

#       # Step 3: Login to Amazon ECR
#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v2

#       # Step 4: Build, tag, and push Docker image
#       - name: Build and Push Docker image
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#           docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest

#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

#       # Step 5: Trigger ECS deployment
#       - name: Force new ECS deployment
#         run: |
#           aws ecs update-service \
#             --cluster $ECS_CLUSTER \
#             --service $ECS_SERVICE \
#             --force-new-deployment

#       # Step 6: Wait for ECS deployment to stabilize
#       - name: Wait for ECS service stability
#         run: |
#           aws ecs wait services-stable \
#             --cluster $ECS_CLUSTER \
#             --services $ECS_SERVICE

#       # Step 7: Deployment completed
#       - name: Deployment Success
#         run: echo "Hourairos deployed successfully!"